// Financial & PO Operations Data Store for Volvitech

export const INITIAL_EXCHANGE_RATES = {
  USD: 1.0,
  INR: 83.20,
  AED: 3.67,
  SAR: 3.75,
};

export const INITIAL_FINANCIAL_KPIS = {
  clientPoTotal: 4850000,
  invoicedTotal: 3420000,
  collectedTotal: 2980000,
  supplierPoCommitted: 2120000,
  supplierBillsBilled: 1650000,
  supplierPaid: 1340000,
  grossMargin: 1770000,
  grossMarginPercent: 51.8,
  arOutstanding: 440000,
  arOverdue: 42500,
  dsoDays: 38,
  apOutstanding: 310000,
  apOverdue: 18200,
  dpoDays: 29,
};

export const INITIAL_PROJECTS_FINANCIALS = [
  {
    id: 'PRJ-2024-01',
    projectName: 'Smart Grid IoT Platform Phase II',
    clientName: 'Gulf Utilities Co.',
    country: 'UAE 🇦🇪',
    currency: 'AED',
    contractValue: 490463, // in USD
    contractValueNative: 1800000,
    invoicedAmount: 367847,
    invoicedPercent: 75,
    supplierCosts: 139800,
    laborCosts: 96200,
    grossMargin: 131847,
    grossMarginPercent: 35.8,
    status: 'Healthy',
    unit: 'Enterprise IoT',
    poNumber: 'PO-GLF-2024-03',
  },
  {
    id: 'PRJ-2024-02',
    projectName: 'Cloud ERP Financial Middleware',
    clientName: 'Riyadh Apex Infrastructure',
    country: 'KSA 🇸🇦',
    currency: 'SAR',
    contractValue: 245333,
    contractValueNative: 920000,
    invoicedAmount: 220800,
    invoicedPercent: 90,
    supplierCosts: 88500,
    laborCosts: 48000,
    grossMargin: 84300,
    grossMarginPercent: 38.2,
    status: 'Healthy',
    unit: 'Fintech Core',
    poNumber: 'PO-KSA-2024-11',
  },
  {
    id: 'PRJ-2024-03',
    projectName: 'Telecom Billing Microservices Engine',
    clientName: 'Tata Communications Ltd',
    country: 'India 🇮🇳',
    currency: 'INR',
    contractValue: 288461,
    contractValueNative: 24000000,
    invoicedAmount: 288461,
    invoicedPercent: 100,
    supplierCosts: 112000,
    laborCosts: 52000,
    grossMargin: 124461,
    grossMarginPercent: 43.1,
    status: 'Completed',
    unit: 'Cloud Infra',
    poNumber: 'PO-IND-2024-88',
  },
  {
    id: 'PRJ-2024-04',
    projectName: 'Algorithmic Ledger Recon Engine',
    clientName: 'Northstar Financial NY',
    country: 'USA 🇺🇸',
    currency: 'USD',
    contractValue: 320000,
    contractValueNative: 320000,
    invoicedAmount: 64000,
    invoicedPercent: 20,
    supplierCosts: 38000,
    laborCosts: 24000,
    grossMargin: 2000,
    grossMarginPercent: 3.1,
    status: 'Margin Risk',
    unit: 'Fintech Core',
    poNumber: 'PO-USA-2024-02',
  },
  {
    id: 'PRJ-2024-05',
    projectName: 'Barclays Open Banking Micro-Gateway',
    clientName: 'Barclays UK Operations',
    country: 'UK 🇬🇧',
    currency: 'USD',
    contractValue: 580000,
    contractValueNative: 580000,
    invoicedAmount: 435000,
    invoicedPercent: 75,
    supplierCosts: 195000,
    laborCosts: 78000,
    grossMargin: 162000,
    grossMarginPercent: 37.2,
    status: 'Healthy',
    unit: 'Fintech Core',
    poNumber: 'PO-BARCLAYS-981',
  },
  {
    id: 'PRJ-2024-06',
    projectName: 'Supply Chain AI Visibility Dashboard',
    clientName: 'NexaCorp International Ltd',
    country: 'USA 🇺🇸',
    currency: 'USD',
    contractValue: 750000,
    contractValueNative: 750000,
    invoicedAmount: 600000,
    invoicedPercent: 80,
    supplierCosts: 290000,
    laborCosts: 165000,
    grossMargin: 145000,
    grossMarginPercent: 24.1,
    status: 'Healthy',
    unit: 'Enterprise Solutions',
    poNumber: 'PO-NX-9901',
  }
];

export const INITIAL_CLIENT_POS = [
  {
    id: 'CPO-001',
    poNumber: 'PO-GLF-2024-03',
    issueDate: '2024-02-14',
    clientName: 'Gulf Utilities Co.',
    flag: '🇦🇪',
    country: 'UAE',
    scope: 'Smart Grid IoT Platform Phase II',
    totalValueNative: 1800000,
    currency: 'AED',
    totalValueUsd: 490463.22,
    invoicedNative: 1350000,
    drawdownPercent: 75,
    remainingNative: 450000,
    remainingPercent: 25.0,
    terms: 'Net 60',
    status: 'Partially Invoiced',
    milestones: [
      { name: 'Milestone 1: Architectural Blueprint', amount: 450000, status: 'Paid', invNum: 'INV-2024-001' },
      { name: 'Milestone 2: Sensor Firmware Integration', amount: 450000, status: 'Paid', invNum: 'INV-2024-018' },
      { name: 'Milestone 3: Cloud Telemetry Pipeline', amount: 450000, status: 'Billed', invNum: 'INV-2024-042' },
      { name: 'Milestone 4: User Acceptance Testing (UAT)', amount: 450000, status: 'Unbilled' },
    ]
  },
  {
    id: 'CPO-002',
    poNumber: 'PO-KSA-2024-11',
    issueDate: '2024-01-28',
    clientName: 'Riyadh Apex Infrastructure',
    flag: '🇸🇦',
    country: 'KSA',
    scope: 'Cloud ERP Financial Middleware',
    totalValueNative: 920000,
    currency: 'SAR',
    totalValueUsd: 245333.15,
    invoicedNative: 828000,
    drawdownPercent: 90,
    remainingNative: 92000,
    remainingPercent: 10.0,
    terms: 'Net 45',
    status: 'Partially Invoiced',
    milestones: [
      { name: 'Initial Sprint 1-6 Middleware Delivery', amount: 460000, status: 'Paid', invNum: 'INV-2024-009' },
      { name: 'ZATCA Phase 2 E-Invoicing Bridge', amount: 368000, status: 'Paid', invNum: 'INV-2024-031' },
      { name: 'Final Production Handover & Signoff', amount: 92000, status: 'Unbilled' },
    ]
  },
  {
    id: 'CPO-003',
    poNumber: 'PO-IND-2024-88',
    issueDate: '2024-01-05',
    clientName: 'Tata Communications Ltd',
    flag: '🇮🇳',
    country: 'India',
    scope: 'Telecom Billing Microservices Engine',
    totalValueNative: 24000000,
    currency: 'INR',
    totalValueUsd: 288461.50,
    invoicedNative: 24000000,
    drawdownPercent: 100,
    remainingNative: 0,
    remainingPercent: 0,
    terms: 'Net 30',
    status: 'Fully Invoiced',
    milestones: [
      { name: 'Architecture Review & Core Setup', amount: 6000000, status: 'Paid', invNum: 'INV-2024-002' },
      { name: 'CDR Parsing Microservice Delivery', amount: 8000000, status: 'Paid', invNum: 'INV-2024-014' },
      { name: 'High-Volume Load Simulation', amount: 6000000, status: 'Paid', invNum: 'INV-2024-025' },
      { name: 'Final Warranty & Go-Live Acceptance', amount: 4000000, status: 'Paid', invNum: 'INV-2024-039' },
    ]
  },
  {
    id: 'CPO-004',
    poNumber: 'PO-USA-2024-02',
    issueDate: '2024-02-18',
    clientName: 'Northstar Financial NY',
    flag: '🇺🇸',
    country: 'USA',
    scope: 'Algorithmic Ledger Recon Engine',
    totalValueNative: 320000,
    currency: 'USD',
    totalValueUsd: 320000,
    invoicedNative: 64000,
    drawdownPercent: 20,
    remainingNative: 256000,
    remainingPercent: 80.0,
    terms: 'Net 30',
    status: 'Open',
    milestones: [
      { name: 'Phase 1: Requirements & SOW Finalization', amount: 64000, status: 'Paid', invNum: 'INV-2024-048' },
      { name: 'Phase 2: Reconciliation Algorithm Testing', amount: 128000, status: 'Unbilled' },
      { name: 'Phase 3: Real-Time Stream Engine', amount: 128000, status: 'Unbilled' },
    ]
  },
  {
    id: 'CPO-005',
    poNumber: 'PO-NX-9901',
    issueDate: '2024-01-10',
    clientName: 'NexaCorp International Ltd',
    flag: '🇺🇸',
    country: 'USA',
    scope: 'Supply Chain AI Visibility Dashboard',
    totalValueNative: 750000,
    currency: 'USD',
    totalValueUsd: 750000,
    invoicedNative: 600000,
    drawdownPercent: 80,
    remainingNative: 150000,
    remainingPercent: 20.0,
    terms: 'Net 45',
    status: 'Partially Invoiced',
    milestones: [
      { name: 'Cloud Architecture & Pipeline', amount: 300000, status: 'Paid', invNum: 'INV-2024-006' },
      { name: 'Predictive Analytics Model Training', amount: 300000, status: 'Paid', invNum: 'INV-2024-029' },
      { name: 'Integration with Global ERP', amount: 150000, status: 'Unbilled' },
    ]
  }
];

export const INITIAL_INVOICES = [
  {
    id: 'INV-001',
    invoiceNumber: 'INV-2024-0042',
    linkedPo: 'PO-GLF-2024-03',
    clientName: 'Gulf Utilities Co.',
    country: 'UAE 🇦🇪',
    issueDate: '2024-03-01',
    dueDate: '2024-05-01',
    amountNative: 450000,
    currency: 'AED',
    amountUsd: 122615.80,
    receivedUsd: 0,
    balanceUsd: 122615.80,
    status: 'Pending',
    milestone: 'Milestone 3: Cloud Telemetry Pipeline',
    taxPercent: 5.0,
  },
  {
    id: 'INV-002',
    invoiceNumber: 'INV-2024-0031',
    linkedPo: 'PO-KSA-2024-11',
    clientName: 'Riyadh Apex Infrastructure',
    country: 'KSA 🇸🇦',
    issueDate: '2024-02-15',
    dueDate: '2024-03-31',
    amountNative: 368000,
    currency: 'SAR',
    amountUsd: 98133.33,
    receivedUsd: 98133.33,
    balanceUsd: 0,
    status: 'Paid',
    milestone: 'ZATCA Phase 2 E-Invoicing Bridge',
    taxPercent: 15.0,
  },
  {
    id: 'INV-003',
    invoiceNumber: 'INV-2024-0048',
    linkedPo: 'PO-USA-2024-02',
    clientName: 'Northstar Financial NY',
    country: 'USA 🇺🇸',
    issueDate: '2024-02-25',
    dueDate: '2024-03-27',
    amountNative: 64000,
    currency: 'USD',
    amountUsd: 64000,
    receivedUsd: 64000,
    balanceUsd: 0,
    status: 'Paid',
    milestone: 'Phase 1: Requirements & SOW Finalization',
    taxPercent: 0,
  },
  {
    id: 'INV-004',
    invoiceNumber: 'INV-2024-0055',
    linkedPo: 'PO-NX-9901',
    clientName: 'NexaCorp International Ltd',
    country: 'USA 🇺🇸',
    issueDate: '2024-03-10',
    dueDate: '2024-04-24',
    amountNative: 150000,
    currency: 'USD',
    amountUsd: 150000,
    receivedUsd: 0,
    balanceUsd: 150000,
    status: 'Pending',
    milestone: 'Predictive Analytics Model Training Part 2',
    taxPercent: 0,
  }
];

export const INITIAL_SUPPLIER_POS = [
  {
    id: 'SPO-001',
    poNumber: 'PO-SUP-2024-114',
    entity: 'Volvitech Tech FZ-LLC',
    supplierName: 'Apex Cloud Infrastructure Ltd',
    origin: 'International (Ireland)',
    taxId: 'IE9822401G',
    linkedProject: 'PRJ-2024-01',
    linkedClientPo: 'PO-GLF-2024-03',
    committedUsd: 140000,
    committedNative: 513800,
    currency: 'AED',
    billedUsd: 110000,
    billedPercent: 78.5,
    remainingUsd: 30000,
    terms: 'Net 30 SWIFT Wire',
    status: 'Partially Invoiced',
    items: [
      { desc: 'Dedicated IoT Cluster Hosting 6 Months', qty: 6, unitPrice: 15000, total: 90000 },
      { desc: 'MQTT Broker High-Throughput Node', qty: 1, unitPrice: 50000, total: 50000 }
    ]
  },
  {
    id: 'SPO-002',
    poNumber: 'PO-SUP-2024-118',
    entity: 'Volvitech India Pvt Ltd',
    supplierName: 'DataCore Systems India Ltd',
    origin: 'Domestic (GST Regular)',
    taxId: '27AAACD1982K1Z9',
    linkedProject: 'PRJ-2024-03',
    linkedClientPo: 'PO-IND-2024-88',
    committedUsd: 139423,
    committedNative: 11600000,
    currency: 'INR',
    billedUsd: 139423,
    billedPercent: 100,
    remainingUsd: 0,
    terms: 'Net 45 NEFT/RTGS',
    status: 'Fulfilled',
    items: [
      { desc: 'Senior Microservices Developers (4 Engineers)', qty: 4, unitPrice: 2000000, total: 8000000 },
      { desc: 'Quality Assurance & Automated Testing SOW', qty: 1, unitPrice: 3600000, total: 3600000 }
    ]
  },
  {
    id: 'SPO-003',
    poNumber: 'PO-SUP-2024-121',
    entity: 'Volvitech US Corp',
    supplierName: 'Nordic CyberSec Solutions',
    origin: 'Import / EEA (Norway)',
    taxId: 'VAT NO981029',
    linkedProject: 'PRJ-2024-05',
    linkedClientPo: 'PO-BARCLAYS-981',
    committedUsd: 260000,
    committedNative: 260000,
    currency: 'USD',
    billedUsd: 65000,
    billedPercent: 25.0,
    remainingUsd: 195000,
    terms: 'Net 30 Fedwire SWIFT',
    status: 'Active Drawdown',
    items: [
      { desc: 'API Security Penetration Testing', qty: 2, unitPrice: 65000, total: 130000 },
      { desc: 'SOC-2 Type II Compliance Audit Module', qty: 1, unitPrice: 130000, total: 130000 }
    ]
  },
  {
    id: 'SPO-004',
    poNumber: 'PO-SUP-2024-129',
    entity: 'Volvitech KSA Branch',
    supplierName: 'Riyadh Telecom Networks',
    origin: 'Domestic KSA (CR 1010892019)',
    taxId: 'CR 1010892019',
    linkedProject: 'PRJ-2024-02',
    linkedClientPo: 'PO-KSA-2024-11',
    committedUsd: 88500,
    committedNative: 331875,
    currency: 'SAR',
    billedUsd: 88500,
    billedPercent: 100,
    remainingUsd: 0,
    terms: 'Net 15 SAR Local Transfer',
    status: 'Bill Overdue',
    items: [
      { desc: 'GCC Dedicated Fiber Tunnel & VPN Peering', qty: 1, unitPrice: 88500, total: 88500 }
    ]
  }
];

export const INITIAL_MASTER_DIRECTORY = [
  {
    id: 'ENT-US-1092',
    name: 'NexaCorp International Ltd.',
    category: 'Client',
    country: 'USA 🇺🇸',
    taxId: 'US-EIN-99210-FX (IRS W-9 Active)',
    contact: 'Marcus Vance (m.vance@nexacorp.com)',
    creditTerms: 'Net 45 (Export Wire)',
    creditLimit: '$250,000',
    currency: 'USD',
    activePoVolume: '$1,850,000 (4 Active Sales POs)',
    compliance: 'Verified',
    docsCount: 6,
  },
  {
    id: 'ENT-AE-3841',
    name: 'Gulf Utilities Co.',
    category: 'Client',
    country: 'UAE 🇦🇪',
    taxId: 'TRN 10028941200003 (FTA Registered)',
    contact: 'Tariq Al-Maktoum (tariq@gulfutilities.ae)',
    creditTerms: 'Net 60 (L/C or Swift)',
    creditLimit: 'Sovereign Backed',
    currency: 'AED',
    activePoVolume: 'AED 4,200,000 (3 Open POs)',
    compliance: 'Expiring Soon (42d left)',
    docsCount: 5,
  },
  {
    id: 'ENT-IN-4912',
    name: 'DataCore Systems India Ltd',
    category: 'Supplier',
    country: 'India 🇮🇳',
    taxId: '27AAACD1982K1Z9 (GST / PAN Regular)',
    contact: 'Rajesh Sharma (finance@datacoreindia.in)',
    creditTerms: 'Net 30 (RTGS / NEFT)',
    creditLimit: 'MSME Tier-1',
    currency: 'INR',
    activePoVolume: '₹32,000,000 (2 Vendor POs)',
    compliance: 'Verified',
    docsCount: 8,
  },
  {
    id: 'ENT-US-8803',
    name: 'CloudScale DevOps LLC',
    category: 'Supplier',
    country: 'USA 🇺🇸',
    taxId: 'US-EIN-44109-CL (W-8BEN Signed)',
    contact: 'Eileen Cole (billing@cloudscale.io)',
    creditTerms: 'Net 30 (ACH Direct)',
    creditLimit: 'Auto-Debit Opted',
    currency: 'USD',
    activePoVolume: '$540,000 (1 Active PO)',
    compliance: 'Verified',
    docsCount: 4,
  },
  {
    id: 'ENT-SA-9014',
    name: 'Riyadh Telecom Networks',
    category: 'Supplier',
    country: 'KSA 🇸🇦',
    taxId: 'CR: 1010892019 (ZATCA e-Inv)',
    contact: 'Fahad Al-Husseini (fahad@riyadhtelecom.sa)',
    creditTerms: 'Net 15 (SADAD Transfer)',
    creditLimit: 'Strict SLA Terms',
    currency: 'SAR',
    activePoVolume: 'SAR 1,120,000 (1 Core PO)',
    compliance: 'Verified',
    docsCount: 5,
  }
];

export const INITIAL_DOCUMENT_VAULT = [
  {
    id: 'DOC-V-01',
    title: 'Standard Client Master Services Agreement (MSA) - Volvitech v4.2',
    category: 'Legal & Contracts',
    fileType: 'PDF',
    size: '1.4 MB',
    updatedDate: '2024-02-10',
    tags: ['Legal', 'MSA', 'Clients', 'Global'],
    url: 'https://docs.google.com/document/d/sample-msa'
  },
  {
    id: 'DOC-V-02',
    title: 'ZATCA E-Invoicing Phase 2 Compliance Specification & Cryptographic Keys',
    category: 'Tax & Compliance',
    fileType: 'PDF',
    size: '890 KB',
    updatedDate: '2024-01-18',
    tags: ['KSA', 'ZATCA', 'Tax', 'E-Invoice'],
    url: 'https://docs.google.com/document/d/sample-zatca'
  },
  {
    id: 'DOC-V-03',
    title: 'UAE Federal Tax Authority (FTA) Corporate Tax & VAT Registration Certificate',
    category: 'Tax & Compliance',
    fileType: 'PDF',
    size: '420 KB',
    updatedDate: '2024-01-05',
    tags: ['UAE', 'VAT', 'TRN', 'FTA'],
    url: 'https://docs.google.com/document/d/sample-fta'
  },
  {
    id: 'DOC-V-04',
    title: 'Volvitech Global Banking Details & SWIFT Wire Routing Directory',
    category: 'Banking & Treasury',
    fileType: 'PDF',
    size: '310 KB',
    updatedDate: '2024-03-01',
    tags: ['Banking', 'Wire Transfer', 'USD', 'AED', 'INR', 'SAR'],
    url: 'https://docs.google.com/document/d/sample-banking'
  },
  {
    id: 'DOC-V-05',
    title: 'Subcontractor Procurement & 3-Way Match Audit SOP',
    category: 'Operations & SOP',
    fileType: 'DOCX',
    size: '560 KB',
    updatedDate: '2024-02-22',
    tags: ['Procurement', '3-Way Match', 'Audit', 'AP'],
    url: 'https://docs.google.com/document/d/sample-sop'
  }
];

// Helper to load or initialize from localStorage
export function loadFinanceData() {
  try {
    const raw = localStorage.getItem('volvitech_finance_suite');
    if (raw) {
      return JSON.parse(raw);
    }
  } catch (e) {
    console.error('Error loading finance data from storage:', e);
  }

  return {
    kpis: INITIAL_FINANCIAL_KPIS,
    exchangeRates: INITIAL_EXCHANGE_RATES,
    projects: INITIAL_PROJECTS_FINANCIALS,
    clientPos: INITIAL_CLIENT_POS,
    invoices: INITIAL_INVOICES,
    supplierPos: INITIAL_SUPPLIER_POS,
    masterDirectory: INITIAL_MASTER_DIRECTORY,
    vault: INITIAL_DOCUMENT_VAULT,
  };
}

export function saveFinanceData(data) {
  try {
    localStorage.setItem('volvitech_finance_suite', JSON.stringify(data));
  } catch (e) {
    console.error('Error saving finance data:', e);
  }
}
